# Generated by Django 4.1.1 on 2022-09-20 15:45
from typing import List

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        verbose_name="Электронная почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация об авторе",
                "verbose_name_plural": "Информация об авторе",
            },
        ),
    ]
