# Generated by Django 4.1.7 on 2023-03-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Информация об авторе"},
        ),
        migrations.AddField(
            model_name="author",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания записи"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время обновления записи"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="link",
            field=models.CharField(max_length=255, verbose_name="Ссылки на резюме"),
        ),
    ]
