# Generated by Django 4.1.7 on 2023-03-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_alter_author_options_author_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="link",
            new_name="resume",
        ),
    ]
